/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMyToken__factory } from "./IMyToken__factory";
export { TinyBank__factory } from "./TinyBank__factory";
