/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tinyBankSol from "./TinyBank.sol";
export { Lock__factory } from "./Lock__factory";
export { MyToken__factory } from "./MyToken__factory";
