/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tinyBankSol from "./TinyBank.sol";
export type { tinyBankSol };
export type { Lock } from "./Lock";
export type { MyToken } from "./MyToken";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { MyToken__factory } from "./factories/MyToken__factory";
export type { IMyToken } from "./TinyBank.sol/IMyToken";
export { IMyToken__factory } from "./factories/TinyBank.sol/IMyToken__factory";
export type { TinyBank } from "./TinyBank.sol/TinyBank";
export { TinyBank__factory } from "./factories/TinyBank.sol/TinyBank__factory";
