/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MultiManagedAccessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BACKUP_MANAGERS_NUMBERS"
      | "MANAGER_NUMBERS"
      | "confirm"
      | "confirmed"
      | "managers"
      | "owner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BACKUP_MANAGERS_NUMBERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGER_NUMBERS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "confirm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "managers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BACKUP_MANAGERS_NUMBERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGER_NUMBERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "confirm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "confirmed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "managers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
}

export interface MultiManagedAccess extends BaseContract {
  connect(runner?: ContractRunner | null): MultiManagedAccess;
  waitForDeployment(): Promise<this>;

  interface: MultiManagedAccessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BACKUP_MANAGERS_NUMBERS: TypedContractMethod<[], [bigint], "view">;

  MANAGER_NUMBERS: TypedContractMethod<[], [bigint], "view">;

  confirm: TypedContractMethod<[], [void], "nonpayable">;

  confirmed: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  managers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BACKUP_MANAGERS_NUMBERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MANAGER_NUMBERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confirm"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "managers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
